# Generated by Django 3.0.8 on 2020-07-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('fullName', models.CharField(max_length=100)),
                ('emailId', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profilePhoto', models.ImageField(upload_to='studentProfile')),
            ],
        ),
    ]
