# Generated by Django 3.0.8 on 2020-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='termsAndCondition',
            field=models.BooleanField(default=False),
        ),
    ]
