# Generated by Django 3.0.8 on 2020-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_studentdetails_termsandcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='password',
            field=models.CharField(max_length=10000),
        ),
    ]
