# Generated by Django 3.0.8 on 2020-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200718_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorDetails',
            fields=[
                ('fullName', models.CharField(max_length=100)),
                ('emailId', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('specialityCourse', models.CharField(max_length=50)),
                ('profilePhoto', models.ImageField(upload_to='tutorProfile')),
            ],
        ),
    ]
