# Generated by Django 3.0.8 on 2020-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_tutordetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutordetails',
            old_name='fullName',
            new_name='firstName',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='mobileNumber',
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='password',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutordetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tutordetails',
            name='profilePhoto',
            field=models.ImageField(null=True, upload_to='tutorProfile'),
        ),
        migrations.AlterField(
            model_name='tutordetails',
            name='specialityCourse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
