# Generated by Django 3.0.8 on 2020-07-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200722_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='loggedIn',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='loggedOut',
        ),
    ]
