# Generated by Django 3.0.8 on 2020-07-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200725_1633'),
        ('Accounts', '0006_auto_20200722_0005'),
    ]

    operations = [
    ]
