# Generated by Django 3.0.8 on 2020-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_tutordetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordetails',
            name='profilePhoto',
            field=models.ImageField(default='Faslse', upload_to='tutorProfile'),
            preserve_default=False,
        ),
    ]
