# Generated by Django 3.0.8 on 2020-08-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20200803_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetails',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='summary',
        ),
    ]
