# Generated by Django 3.0.8 on 2020-08-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_tutorsubjectdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tutorSubjectDetails',
        ),
    ]
