# Generated by Django 3.0.8 on 2020-08-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_tutorsubjectdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsubjectdetails',
            name='address',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubjectdetails',
            name='hourlyPrice1',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubjectdetails',
            name='phoneNumber',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubjectdetails',
            name='subjectName1',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubjectdetails',
            name='subjectName2',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubjectdetails',
            name='subjectName3',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubjectdetails',
            name='summary',
            field=models.CharField(default=' ', max_length=10000, null=True),
        ),
    ]
