# Generated by Django 3.0.8 on 2020-08-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_auto_20200804_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubjectdetails',
            name='hourlyPrice2',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorsubjectdetails',
            name='hourlyPrice3',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
    ]
