# Generated by Django 3.0.8 on 2020-08-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_studentteacherrelationi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentTeacherRelationi',
            new_name='studentTeacherRelation',
        ),
    ]
