# Generated by Django 3.0.8 on 2020-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_auto_20200805_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherStudentRelation',
            fields=[
                ('teacherEmailId', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('studentEmailId', models.TextField(max_length=10000)),
            ],
        ),
    ]
