# Generated by Django 3.0.8 on 2020-08-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_teacherstudentrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentTeacherRelation',
        ),
        migrations.DeleteModel(
            name='teacherStudentRelation',
        ),
    ]
