# Generated by Django 3.0.8 on 2020-08-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_auto_20200827_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentTeacherRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentEmailId', models.EmailField(max_length=254)),
                ('tutorEmailId', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='teacherStudentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorEmailId', models.EmailField(max_length=254)),
                ('studentEmailId', models.EmailField(max_length=254)),
            ],
        ),
    ]
