# Generated by Django 3.0.8 on 2020-08-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_studentteacherrelation_teacherstudentrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorRequestPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorEmailId', models.EmailField(max_length=254)),
                ('studentEmailId', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='tutorStudentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorEmailId', models.EmailField(max_length=254)),
                ('studentEmailId', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='studentTeacherRelation',
            new_name='studentRequestFulfilled',
        ),
        migrations.RenameModel(
            old_name='teacherStudentRelation',
            new_name='studentTutorRelation',
        ),
    ]
