# Generated by Django 3.0.8 on 2020-08-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0024_auto_20200831_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentRequestAccepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentEmailId', models.EmailField(max_length=254)),
                ('tutorEmailId', models.EmailField(max_length=254)),
            ],
        ),
    ]
