# Generated by Django 3.0.8 on 2020-08-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0025_studentrequestaccepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentRequestRejected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentEmailId', models.EmailField(max_length=254)),
                ('tutorEmailId', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='studentRequestAccepted',
            new_name='studentRequestPendingPayment',
        ),
    ]
