# Generated by Django 3.0.8 on 2020-09-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_auto_20200901_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetails',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='lastName',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='fullName',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='termsAndCondition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='fullName',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutordetails',
            name='gender',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
    ]
