# Generated by Django 3.0.8 on 2020-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0030_auto_20200902_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='termsAndCondition',
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='firstName',
            field=models.CharField(default='shashwat singh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='fullName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutordetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
