# Generated by Django 3.0.8 on 2020-09-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0031_auto_20200902_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='newStudentTable',
            fields=[
                ('fullName', models.CharField(max_length=100)),
                ('emailId', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10000)),
                ('profilePhoto', models.ImageField(upload_to='studentProfile')),
                ('gender', models.CharField(default='Male', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='newTutorTable',
            fields=[
                ('fullName', models.CharField(max_length=100)),
                ('emailId', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10000)),
                ('profilePhoto', models.ImageField(upload_to='studentProfile')),
                ('gender', models.CharField(default='Male', max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(default='Male', max_length=24),
        ),
    ]
