# Generated by Django 3.0.8 on 2020-09-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0033_auto_20200902_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequestpending',
            name='subject',
            field=models.CharField(default=' ', max_length=254),
        ),
    ]
