# Generated by Django 3.0.8 on 2020-09-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_tutorrequestpending_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequestpendingpayment',
            name='subject',
            field=models.CharField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='studenttutorrelation',
            name='subject',
            field=models.CharField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='tutorstudentrelation',
            name='subject',
            field=models.CharField(default=' ', max_length=254),
        ),
    ]
