# Generated by Django 3.0.8 on 2020-09-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_studentrequestrejected_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequestfulfilled',
            name='subject',
            field=models.CharField(default='no subject', max_length=254),
            preserve_default=False,
        ),
    ]
